### ISSUE TITLE
Unable to edit project discription

### ISSUE THREAD

**Issue by natedunn** [wwsalmon/project-tracker-frontend#11]
I am unable to edit and save an existing project description. Getting an uncaught promise error. Tested in both Chrome and Firefox.

```
{
  "message": "Syntax Error: Unterminated string.",
  "locations": [
    {
      "line": 6,
      "column": 83
    }
  ]
}
```

![Screen Shot 2020-07-12 at 3 36 28 PM](https://user-images.githubusercontent.com/5555138/87256099-845a5c00-c455-11ea-888f-b6a72326601b.png)

**Comment by wwsalmon** [comment]
Ah gotcha pretty sure I know what's causing this problem -- this error came up a few times elsewhere, I guess I missed a spot when refactoring to fix

**Comment by natedunn** [comment]
No worries! If I had more time I would dig into it more myself.
